# Generated by Django 2.2.7 on 2020-02-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionsAminitrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aminitrator_first_name', models.CharField(blank=True, max_length=30)),
                ('aminitrator_last_name', models.CharField(blank=True, max_length=150)),
                ('aminitrator_email', models.EmailField(blank=True, max_length=254)),
                ('aminitrator_password', models.CharField(max_length=100)),
                ('aminitrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aminitrator_admins', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_elections_aminitrator', 'can view elections aminitrator'),),
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.SmallIntegerField(choices=[(0, '未启动'), (1, '投票中'), (2, '冻结中'), (3, '验证中'), (4, '已完成'), (5, '已结束'), (6, '已废弃')], default=0)),
                ('is_private', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('questions', models.TextField(default='', null=True)),
                ('selections', models.TextField(default='', null=True)),
                ('public_key', models.TextField(default='', null=True)),
                ('verify_file', models.CharField(blank=True, max_length=300)),
                ('vote_result', models.CharField(blank=True, max_length=500)),
                ('selections_message', models.TextField(default='', null=True)),
                ('selections_hash', models.TextField(default='', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionsAminitrator')),
            ],
            options={
                'permissions': (('view_elections', 'can view elections'),),
                'unique_together': {('author', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.EmailField(blank=True, max_length=254)),
                ('voter_password', models.CharField(max_length=100)),
                ('voter_first_name', models.CharField(blank=True, max_length=30)),
                ('voter_last_name', models.CharField(blank=True, max_length=150)),
                ('is_vote', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('vote_g', models.TextField(default='', null=True)),
                ('vote_p', models.TextField(default='', null=True)),
                ('hash_g', models.TextField(default='', null=True)),
                ('hash_p', models.TextField(default='', null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_voters', 'can view voters'),),
                'unique_together': {('voter', 'election')},
            },
        ),
    ]
